[package]
name = "stochastic-predator-prey"
version = "0.1.0"
authors = ["robertjankowski <robjanw11@wp.pl>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
rand_distr = "0.2.2"
itertools-num = "0.1.3"